require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
$RNFirebaseAnalyticsWithoutAdIdSupport = true

target 'B7International' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'JitsiMeetSDK'


  target 'B7InternationalTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
  end
end

target 'B7International-tvOS' do
  # Pods for B7International-tvOS

  target 'B7International-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
